name: Build DirectPlay (dummy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up MinGW
        run: |
          choco install mingw -y

      - name: Force 32-bit MinGW
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_PATH "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin"

      - name: Check GCC version and arch
        run: |
          gcc -v
          gcc -dumpmachine

      - name: Compile DLL
        run: |
          gcc -m32 -shared -o dplay.dll dllmain.c dplay.def

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: dplay
          path: |
            dplay.dll
