name: Build DirectPlay (dummy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: mingw-w64-i686-gcc

      - name: Check GCC version and arch
        run: |
          gcc -v
          gcc -dumpmachine

      - name: Compile DLL
        shell: msys2 {0}
        run: |
          gcc -m32 -shared -o dplay.dll dllmain.c dplay.def

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: dplay
          path: |
            dplay.dll
